### ISSUE TITLE
Excel macro did not run

### ISSUE THREAD

**Issue by dlparkhurst** [usgs-coupled/iphreeqc#44]
I installed 32- and 64-bit IPhreeqcCOMs and restarted my computer.

I compiled and installed iphreeqc and opened the excel file:
_build\INSTALL\examples\com\excel\runphreeqc.xls
went to view->macros, run runphreeqc gave the error message" Runtime error '424', Object required"

Did I miss a step?

**Comment by scharlton2** [comment]
Note that Powershell examples have been added to the IPhreeqcCOM documentation.

Opening a powershell terminal is probably the easiest way to debug IPhreeqcCOM errors.

In a powershell window try:

$iphreeqc = New-Object -ComObject IPhreeqcCOM.Object

The absence of output typically indicates success.

As for the problem you're having I suspect that the .NET Framework 3.5 needs to be enabled.  For instructions please see the following:

https://gist.github.com/scharlton2/b8dd1ccd2820c62859c8e7ac5d1ccc2e
